version: '3.0'

services:
  frontend:
    container_name: dailyfocus-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # env_file:
    #   - ./frontend/.env
    restart: always
    ports:
      - "${frontend_port}:3000"
    depends_on:
      - backend
    networks:
      - dailyfocus
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"

  backend:
    container_name: dailyfocus-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    restart: always
    ports:
      - "${backend_port}:5000"
    depends_on:
      - db
    networks:
      - dailyfocus
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"

  db:
    image: mysql
    container_name: dailyfocus-mysql
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "${db_port}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dailyfocus

volumes:
  mysql_data:
networks:
  dailyfocus: